# Generated by Django 3.1.6 on 2021-02-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210215_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='kind',
            new_name='profile_type',
        ),
    ]
