# Generated by Django 3.1.6 on 2021-02-15 08:01

from django.db import migrations
import unidigi.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210215_0737'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', unidigi.users.models.UnidigiUserManager()),
            ],
        ),
    ]
